import {Manrope } from "next/font/google";
import "./globals.css";
import Navber from "@/components/Navber";
import Footer from "@/components/Footer";

const manRope= Manrope({
    variable: "--font-man-rope",
  subsets: ["latin"],
})


export const metadata = {
  title: "HireLoop",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      data-theme="dark"
      className={`${manRope.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Navber/>
        {children}
        </body>
        <Footer/>
    </html>
  );
}
