import { Manrope } from "next/font/google";
import "./globals.css";
import Navber from "@/components/Navber";
import { ToastContainer } from "react-toastify";

const manRope = Manrope({
  variable: "--font-man-rope",
  subsets: ["latin"],
})


export const metadata = {
  title: "HireLoop",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      data-theme="dark"
      className={`${manRope.className} h-full antialiased`}
    >
      <body>
        <Navber />
        {children}
        <ToastContainer />
      </body>
    </html>
  );
}
